### ISSUE TITLE
login with google

### ISSUE THREAD

**Issue by mqurishi** [ryuseisan/auto-chatgpt#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ryuseisan** [comment]
Hello mqurishi,

First of all, I would like to thank you for your interest in this project and for your input. Your valuable feedback will be very helpful in moving this project forward.

Regarding the Google login feature you mentioned, the login_google_account() function in autochatgpt/login.py used to support this. However, due to refactoring in commit 02fa7e5f67cabbf58d31b0ec8d2bb052d4e03981, it is no longer supported.

I am aware of this issue and have already begun work on a fix. We will post an update as soon as this issue is completed. In the meantime, we ask for your patience.

If you have any additional information or encounter any problems, please do not hesitate to contact us. Thank you in advance for your cooperation.

**Comment by ryuseisan** [comment]
Sorry, we do not yet support 2-step verification.
